version: '3.4'

networks:
  static:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
  standard:

volumes:
  l1_data:
  l2_data:
  l2_builder_data:
  op_log:

services:
  l1:
    networks:
      - standard
    build:
      context: .
      dockerfile: Dockerfile.l1
    ports:
      - "8545:8545"
      - "8546:8546"
      - "7060:6060"
    volumes:
      - "l1_data:/db"
      - "${PWD}/../.devnet/genesis-l1.json:/genesis.json"
      - "${PWD}/test-jwt-secret.txt:/config/test-jwt-secret.txt"

  l2:
    networks:
      static:
        ipv4_address: 172.20.0.6
      standard:
    build:
      context: .
      dockerfile: Dockerfile.l2
    ports:
      - "9545:8545"
      - "9551:8551"
      - "18060:6060"
    volumes:
      - "l2_data:/db"
      - "${PWD}/../.devnet/genesis-l2.json:/genesis.json"
      - "${PWD}/test-jwt-secret.txt:/config/test-jwt-secret.txt"
    entrypoint:  # pass the L2 specific flags by overriding the entry-point and adding extra arguments
      - "/bin/sh"
      - "/entrypoint.sh"
      - "--authrpc.jwtsecret=/config/test-jwt-secret.txt"
      - "--nodekeyhex=b02c978bf3fb3ba2e491d4d8a715c14005160db258e45ef943e161161ace2992"
      - "--nat=extip:172.20.0.6"

  op-node:
    restart: on-failure:5
    networks:
      static:
        ipv4_address: 172.20.0.7
      standard:
    depends_on:
      - l1
      - l2
    build:
      context: ../
      dockerfile: ./op-node/Dockerfile
    command: >
      op-node
      --l1=ws://l1:8546
      --l2=http://l2:8551
      --l2.jwt-secret=/config/test-jwt-secret.txt
      --sequencer.enabled
      --sequencer.l1-confs=0
      --verifier.l1-confs=0
      --p2p.sequencer.key=8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba
      --rollup.config=/rollup.json
      --rpc.addr=0.0.0.0
      --rpc.port=8545
      --p2p.advertise.ip=172.20.0.7
      --p2p.listen.ip=0.0.0.0
      --p2p.listen.tcp=9003
      --p2p.listen.udp=9003
      --p2p.scoring.peers=light
      --snapshotlog.file=/op_log/snapshot.log
      --p2p.priv.path=/config/p2p-node-key.txt
      --metrics.enabled
      --metrics.addr=0.0.0.0
      --metrics.port=7300
      --pprof.enabled
      --rpc.enable-admin
      --mev.api=http://l2-builder:28545
    ports:
      - "7545:8545"
      - "7546:8546"
      - "9003:9003"
      - "7300:7300"
      - "6060:6060"
    volumes:
      - "${PWD}/p2p-sequencer-key.txt:/config/p2p-sequencer-key.txt"
      - "${PWD}/p2p-node-key.txt:/config/p2p-node-key.txt"
      - "${PWD}/test-jwt-secret.txt:/config/test-jwt-secret.txt"
      - "${PWD}/../.devnet/rollup.json:/rollup.json"
      - op_log:/op_log

  op-batcher:
    restart: on-failure:5
    networks:
      - standard
    depends_on:
      - l1
      - l2
      - op-node
    build:
      context: ../
      dockerfile: ./op-batcher/Dockerfile
    ports:
      - "6061:6060"
      - "7301:7300"
      - "6545:8545"

    environment:
      OP_BATCHER_L1_ETH_RPC: http://l1:8545
      OP_BATCHER_L2_ETH_RPC: http://l2:8545
      OP_BATCHER_ROLLUP_RPC: http://op-node:8545
      OP_BATCHER_MAX_CHANNEL_DURATION: 1
      OP_BATCHER_SUB_SAFETY_MARGIN: 4 # SWS is 15, ChannelTimeout is 40
      OP_BATCHER_POLL_INTERVAL: 1s
      OP_BATCHER_NUM_CONFIRMATIONS: 1
      OP_BATCHER_MNEMONIC: test test test test test test test test test test test junk
      OP_BATCHER_SEQUENCER_HD_PATH: "m/44'/60'/0'/0/2"
      OP_BATCHER_PPROF_ENABLED: "true"
      OP_BATCHER_METRICS_ENABLED: "true"
      OP_BATCHER_RPC_ENABLE_ADMIN: "true"

  op-proposer:
    restart: on-failure:5
    networks:
      - standard
    depends_on:
      - l1
      - l2
      - op-node
    build:
      context: ../
      dockerfile: ./op-proposer/Dockerfile
    ports:
      - "6062:6060"
      - "7302:7300"
    environment:
      OP_PROPOSER_L1_ETH_RPC: http://l1:8545
      OP_PROPOSER_ROLLUP_RPC: http://op-node:8545
      OP_PROPOSER_POLL_INTERVAL: 1s
      OP_PROPOSER_NUM_CONFIRMATIONS: 1
      OP_PROPOSER_MNEMONIC: test test test test test test test test test test test junk
      OP_PROPOSER_L2_OUTPUT_HD_PATH: "m/44'/60'/0'/0/1"
      OP_PROPOSER_L2OO_ADDRESS: "${L2OO_ADDRESS}"
      OP_PROPOSER_PPROF_ENABLED: "true"
      OP_PROPOSER_METRICS_ENABLED: "true"
      OP_PROPOSER_ALLOW_NON_FINALIZED: "true"


  stateviz:
    networks:
      - standard
    build:
      context: ../
      dockerfile: ./ops-bedrock/Dockerfile.stateviz
    command:
      - stateviz
      - -addr=0.0.0.0:8080
      - -snapshot=/op_log/snapshot.log
      - -refresh=10s
    ports:
      - "9090:8080"
    volumes:
      - op_log:/op_log:ro

  l2-builder:
    networks:
      static:
        ipv4_address: 172.20.0.8
      standard:
    build: # with this the EL is not able to sync
      context: ../../fb-builder/
    # build:
    #   context: .
    #   dockerfile: Dockerfile.l2
    depends_on:
      - l1
      - l2
      - op-node
    ports:
      - "9500:8545"
      - "9501:8551"
      - "18061:6060"
    volumes:
      - "l2_builder_data:/db"
      - "${PWD}/../.devnet/genesis-l2.json:/genesis.json"
      - "${PWD}/test-jwt-secret.txt:/config/test-jwt-secret.txt"
    entrypoint:  # pass the L2 specific flags by overriding the entry-point and adding extra arguments
      - "/bin/sh"
      - "/entrypoint.sh"
      - "--authrpc.jwtsecret=/config/test-jwt-secret.txt"
      - "--nat=extip:172.20.0.8"
      - "--builder"
      - "--builder.local_relay"
      - "--builder.seconds_in_slot=2"
      - "--builder.submission_offset=1s"
      - "--builder.beacon_endpoints=http://op-node-builder:8501"
      - "--miner.extradata=IlluminateDmocratizeDstribute"
      - "--miner.algotype=greedy"
      - "--bootnodes=enode://95f711311375a92cbc3c16f4f1e9147f69fe45ff73c3ce71202d3e78628bd545fb2441c539165c48361e1cbbb0d06d19e46e80ecee8729d2810932092dc0143d@172.20.0.6:30303"

  op-node-builder:
    restart: on-failure:5
    networks:
      static:
        ipv4_address: 172.20.0.9
      standard:
    depends_on:
      - l1
      - l2
      - op-node
      - l2-builder
    build:
      context: ../
      dockerfile: ./op-node/Dockerfile
    command: >
      op-node
      --l1=ws://l1:8546
      --l2=http://l2-builder:8551
      --l2.jwt-secret=/config/test-jwt-secret.txt
      --rollup.config=/rollup.json
      --rpc.addr=0.0.0.0
      --rpc.port=8500
      --rpc.enable-admin
      --p2p.bootnodes=${ENR}

    ports:
      - "7500:8500"
      - "7501:8501"
    volumes:
      - "${PWD}/test-jwt-secret.txt:/config/test-jwt-secret.txt"
      - "${PWD}/../.devnet/rollup.json:/rollup.json"
      - op_log:/op_log
