FROM mcr.microsoft.com/dotnet/sdk:7.0-jammy

RUN apt-get update && apt-get -y install libsnappy-dev libc6-dev libc6

# Fix rocksdb issue in ubuntu 22.04 (assumes amd64)
# RUN ln -s /usr/lib/x86_64-linux-gnu/libdl.so.2 /usr/lib/x86_64-linux-gnu/libdl.so > /dev/null 2>&1
